pymc-devs/pymc-extras

- pymc_experimental/__init__.py
- pymc_experimental/bart/__init__.py
- pymc_experimental/bart/bart.py
- pymc_experimental/bart/pgbart.py
- pymc_experimental/bart/tree.py
- pymc_experimental/bart/utils.py
- pymc_experimental/tests/__init__.py
- pymc_experimental/tests/test_bart.py
This is already usable, for example 
```python
with pm.Model() as model:
σ = pm.HalfNormal("σ", Y.std())
μ = pmx.BART("μ", X, Y)
y = pm.Normal("y", μ, σ, observed=Y)
idata = pm.sample()
```
will work, but still one features is missing compared to the PyMC version from the main repository.
* The functions in `utils` need to be changed or we need to change how we store the `samples_stats`: `variable_importance` and `bart_trees`. We used to do this preprocessing. 
* https://github.com/pymc-devs/pymc/compare/main...aloctavodia:byebyebart?expand=1#diff-7b3470589153c7c90a2c05fc86402f9acf65555200d90f01b51a47ccef592628L637-L654
I will fix that in a separated PR.
> Move bart from PyMC

- README.md
Since we're already migrating things from `pymc` and I have also recommended `pymc-experimental` as the place for contributing new step methods, I updated the readme.
The changes should reflect that we're slowing committing to `pymc-experimental` being a thing, while openly communicating the unresolved things.
I also added line breaks between sentences to simplify the git diffs in the long term. This doesn't affect the final formatting.
Closes #1 (?)
> Rephrase to reflect maturation of the project

- pymc_experimental/bart/pgbart.py
- pymc_experimental/bart/tree.py
- pymc_experimental/bart/utils.py
- pymc_experimental/tests/test_bart.py
The total number of trees is `draw` x `chains` x `m`, this can lead to a high memory use. This PR reduces the memory by removing attributes from trees before saving. The removed attributes are used during fitting but not after.
> Reduce tree size before saving them

- pymc_experimental/bart/bart.py
- pymc_experimental/bart/pgbart.py
- pymc_experimental/bart/tree.py
This removes the need to set the value of `k`, that affects the  value of mu_std. We now instead sample k from a uniform distribution when particles are created during tuning.
Additionally in this PR we:
* Refactor `init_particles`,
* Remove `max_stages` because is not actually needed
* Other small changes to make code more clear to read
> Remove k argument

- pymc_experimental/gp/latent_approx.py
The `infer_size` function was removed, because it was an overcomplicated way of doing `np.shape(.)[0]`.
`np.shape(tensor)` simply returns `tensor.shape` and since `size` can be symbolic, we don't care if it's numeric or not.
Closes #44
> Replace uses of remove `pm.gp.util.infer_size` function

- pymc_experimental/bart/bart.py
- pymc_experimental/bart/pgbart.py
- pymc_experimental/bart/tree.py
- pymc_experimental/bart/utils.py
- pymc_experimental/tests/test_bart.py
This allows fully non-parametrical models of the form
```python
with pm.Model() as model:
w = pmx.BART("w", X, Y, shape=2)
μ = pm.Deterministic("μ", w[0])
σ = pm.Deterministic("σ", np.abs(w[1]))
y = pm.Normal("y", μ, σ, observed=Y)
```
or models where the Y is not 1D.
> BART: add shape argument

- pymc_experimental/bart/tree.py
- pymc_experimental/bart/utils.py
Also sort the variables by default when plotting variable importance.
> BART-VI use mean of leaf nodes when prunning instead of zero

- docs/api_reference.rst
- pymc_experimental/tests/test_prior_from_trace.py
- pymc_experimental/utils/__init__.py
- pymc_experimental/utils/prior.py
If you want to do knowledge transfer in a smart way, this is how you do this
```python
from pymc.distributions import transforms
with model1:
trace = pm.sample()
with pm.Model(coords=dict(test=range(3))) as model:
priors = pmx.utils.prior.prior_from_idata(
trace, 
var_names=["a"],
b=("test", "test"),
c=transforms.log, 
d="e", 
f=dict(dims="test"),
g=dict(name="h", dims="test", transform=transforms.log)
)
```
> Initialize a prior from a fitted posterior

- .gitignore
- .gitpod.yml
Seems like prebuilds cache in the workspace directory and everything else is from scratch
> prebuilds setup

- .github/workflows/test.yml
- conda-envs/environment-test-py38.yml
- conda-envs/environment-test-py39.yml
- pymc_experimental/__init__.py
- pymc_experimental/bart/__init__.py
- pymc_experimental/inference/__init__.py
- pymc_experimental/inference/fit.py
- pymc_experimental/inference/pathfinder.py
- pymc_experimental/tests/test_pathfinder.py
- requirements-dev.txt
- requirements.txt
Lot's of help from @ricardoV94 
CC @rlouf
> Add wrapper for running blackjax pathfinder

- pymc_experimental/model_builder.py
- pymc_experimental/tests/test_model_builder.py
fixes #88
@twiecki @drbenvincent
> added predict_posterior

- pymc_experimental/distributions/histogram_utils.py
- requirements.txt
- setup.py
> Make xhistogram dependency optional

- pymc_experimental/model_builder.py
- pymc_experimental/tests/test_model_builder.py
Extending the model_builder test suite
> Model builder tests

- pymc_experimental/model_builder.py
Closes #120.
As requested in issue #120 model_config and sampler_config instead of being stored in idata.attrs separately as dict keys and dict values are stored in single json string idata.attrs['sampler_config'] and idata.attrs['model_config']. 
No test adaptation was necessary
> storing model_config and sampler_config changed to json string

- docs/_templates/autosummary/base.rst
- docs/_templates/autosummary/class.rst
- docs/api_reference.rst
- docs/conf.py
- docs/index.rst
- pymc_experimental/distributions/continuous.py
- pymc_experimental/marginal_model.py
- requirements-docs.txt
Probably I have syntax issues: CC @OriolAbril 
Not sure what GP stuff should be listed: CC @bwengals 
Closes #101
> Update API reference listings

- pymc_experimental/tests/test_marginal_model.py
> Seed flaky test

- .github/release.yml
- .github/workflows/release.yml
- setup.py
Added release.yml
changed long_description_type to text/markdown, pypi check was rejecting the content of the README.md with the previous type
> release preparation

- pymc_experimental/model_builder.py
- pymc_experimental/tests/test_model_builder.py
Updates the docstrings in model_builder.py , ensures that they follow the numpydoc conventions
> docstrings update in model_builder.py

- pymc_experimental/tests/distributions/test_discrete_markov_chain.py
The test was failing because the result was not equal up to 10+ digit, I assumed that 6 digit precision should be good enough in this case, now the test is passing
> fixed test failing due to infinite precision requirement

- pymc_experimental/bayesian_estimator_linearmodel.py
- pymc_experimental/model_builder.py
- pymc_experimental/tests/test_bayesian_estimator_linearmodel.py
> Initial draft of version of model_builder to work with scikit-learn.

- docs/api_reference.rst
- pymc_experimental/tests/utils/test_model_fgraph.py
- pymc_experimental/utils/__init__.py
- pymc_experimental/utils/model_fgraph.py
- pymc_experimental/utils/pytensorf.py
```python
from pytensor import dprint
from pymc_experimental.utils.model_fgraph import fgraph_from_model, model_from_fgraph
with pm.Model (coords={"trial": range(3)}) as m:
y_obs = pm.MutableData("y_obs", [1., 2., 3.], dims=("trial",))
mu = pm.Normal("mu")
sigma = pm.HalfNormal("sigma")
y = pm.Normal("y", mu, sigma, observed=y_obs, dims=("trial",))
pm.model_to_graphviz(m)
fg = fgraph_from_model(m)
dprint(fg)
... # Manipulate model
new_m = model_from_fgraph(fg)
pm.model_to_graphviz(new_m)
```
> Add utility to convert Model to and from FunctionGraph

- .github/workflows/pypi.yml
GitHub Actions doesn't yet support the slicing operations, therefore the slicing needs to be used after retrieving the github.ref_name for comparison.
> replacing slicing in git actions with python slicing

- pymc_experimental/model_builder.py
- pymc_experimental/tests/test_linearmodel.py
Fixes #184 by allowing `random_seed` to be set in calls to `predict` in `test_save_load` for `LinearModel`.
> Pass kwargs through to pymc sample calls

- docs/api_reference.rst
- pymc_experimental/model_transform/basic.py
- pymc_experimental/model_transform/conditioning.py
- pymc_experimental/tests/model_transform/test_basic.py
- pymc_experimental/tests/model_transform/test_conditioning.py
- pymc_experimental/tests/utils/test_model_fgraph.py
- pymc_experimental/utils/model_fgraph.py
- pymc_experimental/utils/pytensorf.py
```python
from pymc_experimental.model_transform.conditioning import do
with pm.Model() as m:
x = pm.Normal("x", 0, 1)
y = pm.Normal("y", x, 1)
z = pm.Normal("z", y + x, 1)
idata_m = az.from_dict({rv.name: [pm.draw(rv, draws=500)] for rv in [x, y, z]})
m_do = do(m, {y: 100.0})
with m_do:
idata_do = pm.sample_posterior_predictive(idata_m, var_names="z")
```
> Implement observe and do transformations

- pymc_experimental/distributions/timeseries.py
- pymc_experimental/marginal_model.py
- requirements.txt
pymc 5.5.0 has removed ignore_logprob function therefore it's imports need to be removed on pymc-experimental side
> Update to pymc 5.5.0

- pymc_experimental/tests/distributions/test_discrete_markov_chain.py
- pymc_experimental/tests/model_transform/test_conditioning.py
- pymc_experimental/tests/utils/test_model_fgraph.py
Fixes #192
Added seeding to tests that draw from random variables and check the values drawn.
> Added seeding to draws in tests

- pymc_experimental/model_builder.py
- pymc_experimental/tests/test_model_builder.py
In response to #196, I made an attempt at the refactoring.
The first commit naively duplicates the existing `fit` function for both mcmc and find_MAP fitting methods. The fourth commit puts some of the setup and cleanup code back in the `fit` function and switches only the actual inference part. I didn't know which way the team might prefer, so they're both there.
I considered making an `Enum` for the fitting methods, but I saw that `pymc.sampling.sample()` uses `str`, so that's what I did here.
I don't feel great about the handling of `sampler_config` arguments here. There is some overlap in args to mcmc `sample_*` and `find_MAP`, but some args are different. At least `scipy.optimize.minimize` doesn't accept extraneous kwargs, so I pass through only whitelisted args to `find_MAP`.
> Refactor modelbuilder fit

- pymc_experimental/distributions/multivariate/r2d2m2cp.py
- pymc_experimental/tests/distributions/test_multivariate.py
close #170 to enable strict coefficient sign in the model
```python
with pm.Model(coords=dict(a=range(2))) as model:
std, beta = pmx.distributions.R2D2M2CP(
"beta1",
1,
[1, 1],
dims="a",
r2=0.8,
r2_std=0.1,
positive_probs=[0.5, 0],
positive_probs_std=[0.3, 0],
centered=False,
)
```
> Implement limit case of R2D2M2CP for P

- pymc_experimental/model_builder.py
- pymc_experimental/tests/test_model_builder.py
Reverts pymc-devs/pymc-experimental#198
The solution wasn't tested In practice yet. It might be merged in the future once it's applicability to models other than CLV models will be proven.
> Revert "Refactor modelbuilder fit"

- pymc_experimental/distributions/multivariate/r2d2m2cp.py
When reparametrizing sigma into explained variance + residual sigma, tau is not needed any more, but was mistakenly used in the model that led to instabilities and incorrect interpretation.
Related to #206
> Fix math in sigma attachment

- pymc_experimental/linearmodel.py
- pymc_experimental/model_builder.py
- pymc_experimental/tests/test_linearmodel.py
- pymc_experimental/tests/test_model_builder.py
fixing dims format, enabling input param preservation.
The fixes needed to be applied for models that take input parameters that aren't included in the dataset. Furthermore the json conversion was changing dims from tuple to a list, which was in the end changing model id and failing the load function
> ModelBuilder.load versatility improvements

- pymc_experimental/tests/utils/test_model_fgraph.py
- pymc_experimental/utils/model_fgraph.py
In earlier iterations of the do-blogpost it became clear that it's more intuitive for model-related shared variables to be copied, instead of shared across different models. Some of these variables are created by PyMC (dim_lengths) and users would have to know the internals not to be surprised about the behavior.
User defined `MutableData` is also copied, because unlike the underlying `SharedVariable`s, nothing about the name and documentation suggests these variables are supposed to be "shared" across models (just that they can be mutated).
I have only allowed user-defined shared variables that are *not* model variables to be actually shared across model cloning.
This now works as (imo) expected:
```python
from pymc_experimental.model_transform.conditioning import do …
```
> Copy model-related shared variables in `model_fgraph`

- pymc_experimental/model_builder.py
- pymc_experimental/tests/__init__.py
- pymc_experimental/tests/test_model_builder.py
- setup.cfg
fixing json formatting for model_config
> fixing second loading issue

- docs/api_reference.rst
- pymc_experimental/model_transform/basic.py
- pymc_experimental/model_transform/conditioning.py
- pymc_experimental/tests/model_transform/test_conditioning.py
Provides a cleaner solution to use cases like https://github.com/pymc-devs/pymc/issues/5443
> Implement utility to change value variable transforms

- pymc_experimental/model_transform/conditioning.py
- pymc_experimental/tests/model_transform/test_conditioning.py
This is now possible:
```python
from pymc_experimental.model_transform.conditioning import do
with pm.Model() as m:
x = pm.Normal("x")
new_m = do(m, {x: x + 100})
assert pm.draw(new_m["do_x"] > 50)
```
It was already fine to do this kind of  replacement with `Deterministics` (or other RVs) as is the following:
```python
with pm.Model() as m:
x = pm.Normal("x")
do_x = pm.Deterministic("det", x)
new_m = do(m, {det: x + 100})
assert pm.draw(new_m["det"] > 50)
```
```python
with pm.Model() as m:
x = pm.Normal("x")
y = pm.Normal("y", x)
new_m = do(m, {y: x + 100})
assert pm.draw(new_m["y"] > 50)
```
> Allow do interventions to reference intervened variable

- pymc_experimental/linearmodel.py
- pymc_experimental/model_builder.py
- pymc_experimental/tests/test_model_builder.py
while renaming the abstract definition, the function call in fit() was left over with old name. This requires quick bug fix
> renamed to _generate_and_preprocess_model_data

- pymc_experimental/tests/test_model_builder.py
Fixes #212 by setting tune=1, draws=1 in model_builder test_fit_no_y test.
> Speed up test_fit_no_y

- pymc_experimental/linearmodel.py
- pymc_experimental/model_builder.py
- pymc_experimental/tests/test_model_builder.py
Fixes #225. Since the method changed from a property to a method, it was renamed from a noun to a verb. Both `default_model_config` and `default_sampler_config` were changed.
> Change default_*_config from @property to @staticmethod

- .github/workflows/test.yml
- docs/api_reference.rst
- pymc_experimental/distributions/__init__.py
- pymc_experimental/distributions/continuous.py
- pymc_experimental/tests/distributions/test_continuous.py
- pymc_experimental/tests/distributions/test_multivariate.py
Following the discussion [here](https://github.com/pymc-devs/pymc/discussions/6905) and obsolete PRs [here](https://github.com/pymc-devs/pytensor/pull/440) and [here](https://github.com/pymc-devs/pymc/pull/6907), I have attempted to implement a Chi distribution helper class using `CustomDist`.
The distribution is functionally correct in that it is able to reproduce the `scipy` chi PDF.
There is an issue with adding this distribution to a `pymc` model, however. For example:
```python
from pymc_experimental.distributions import Chi
with pm.Model() as model:
pm.Chi("x", df=1)
print(model.initial_point())
```
results in
```
TypeError: Cannot convert Type Scalar(float64, shape=()) (of Variable Exp.0) into Type Vector(float64, shape=(1,)). You can try to manually convert Exp.0 …
```
> Implement Chi distribution helper

- docs/api_reference.rst
- pymc_experimental/distributions/__init__.py
- pymc_experimental/distributions/discrete.py
- pymc_experimental/tests/distributions/test_discrete.py
Closes #197  Add skellam using the CustomDist
Doc rendering:
> Implement Skellam distribution

- docs/api_reference.rst
- pymc_experimental/distributions/__init__.py
- pymc_experimental/distributions/continuous.py
- pymc_experimental/tests/distributions/test_continuous.py
Have the logp tests working like the other two distributions. I tried to implement the logcdf but am hitting some difficulties with those. The values are relatively close but are off by only a decimal in a few cases. I'm checking the translation from wikipedia formula and will look for some simplifications if possible. I see the scipy implements like [this](https://github.com/scipy/scipy/blob/f990b1d2471748c79bc4260baf8923db0a5248af/scipy/stats/_continuous_distns.py#L6299-L6300). If anything is obvious, let me know
> Implement Maxwell Distribution

- pymc_experimental/linearmodel.py
- pymc_experimental/model_builder.py
- pymc_experimental/tests/test_linearmodel.py
- pymc_experimental/tests/test_model_builder.py
Fixes #248 
I also have a commit in here with some clean-up to `ModelBuilder.sample_prior_predictive` that I saw while working on this. It's unrelated but relatively minor.
> Set data when building Linearmodel

- conda-envs/environment-test.yml
- conda-envs/windows-environment-test.yml
- pymc_experimental/model/marginal_model.py
- pymc_experimental/utils/prior.py
- requirements.txt
Changing the name to reflect the renaming in https://github.com/pymc-devs/pymc/commit/04a03b520aa52c5586123f076c6377b32cf855b4
Otherwise importing this module raises an import error.
This need not be merged now, I am just making this PR to use the commit in my dependencies without relying on my own fork.
> Adapt PyMC 5.10.0 breaking changes

- docs/api_reference.rst
- pymc_experimental/model/transforms/autoreparam.py
- pymc_experimental/tests/model/transforms/test_autoreparam.py
- pymc_experimental/utils/autoreparam.py
This PR adds a tool to autoparameterize your model in the following way: https://arxiv.org/abs/1906.03028
The intended api is like this
You need to convert tour model to change its structure
Then you use your samplers
For stability, you might want to turn on clipping for lambdas
> Variationally Informed Parameterization

- pymc_experimental/model/model_api.py
- pymc_experimental/tests/model/test_model_api.py
This commits the second approach described in #275 allowing coords to be updated when the model function is called.
> Pass coords argument into model factory

- pymc_experimental/statespace/models/structural.py
- pymc_experimental/tests/statespace/test_structural.py
Closes #281
Closes #289 
The CycleComponent should have 2 states -- `[cycle_sin, cycle_cos]`, and associated dims. I had incorrectly assigned it only a single initial state, so the cosine component was forced to always be zero at initialization.
In addition, `model.param_dims` will now correctly return named dims for the cycle initial state.
Adds a test of model initial states against statsmodels to catch issues like this in the future.
> Fix initial state size in CycleComponent

- pymc_experimental/model/marginal_model.py
- pymc_experimental/tests/model/test_marginal_model.py
This is a PR to add support for the `recover_marginals` method. This allows us to sample values and get access to the logps of discrete variables which we marginalized out during sampling.
Closes #286
> Implement utility to recover marginalized variables from `MarginalModel`

- pymc_experimental/model/marginal_model.py
Removes the use of `treedict` where an ordinary dictionary is good-enough
Closes #291
> Remove use of treedict, addresses #291

- pymc_experimental/statespace/models/SARIMAX.py
- pymc_experimental/statespace/models/structural.py
- pymc_experimental/tests/statespace/test_SARIMAX.py
- pymc_experimental/tests/statespace/test_structural.py
Closes #295 
Variables named "sigma" in structural models, as well as SARIMAX, were being directly inserted into the state/observation covariance matrix as-is. This implies they are variances, while the name "sigma" suggests they are standard deviations.
This PR squares parameters named "sigma" before inserting them into the appropriate covariance matrices to avoid surprising users due to incorrect naming convention.
> Use model variables named "sigma" as standard deviations rather than variances

- pymc_experimental/model/marginal_model.py
- pymc_experimental/tests/model/test_marginal_model.py
Closes #303 
We have to move towards using `clone_model` fgraph functionality which handles all sorts of models, but that requires quite a bit more of refactoring
> Fix MarginalModel with Data containers

- pyproject.toml
Closes #305 
JAX warning mentioned https://github.com/pymc-devs/pymc-experimental/issues/305 seems to be caused by using multiple cores when sampling with pm.sample in tests. The JAX test appears to be over-eager, because it is issued even when JAX is not being used, as long as JAX has been imported. 
This PR adds the warning to `filterwarnings` in the `pyproject.toml`, since it doesn't appear to be relevant to the tests its causing to fail.
> Fix JAX warnings in tests

- pymc_experimental/statespace/core/representation.py
- pymc_experimental/statespace/core/statespace.py
- pymc_experimental/statespace/filters/distributions.py
- pymc_experimental/statespace/filters/kalman_filter.py
- pymc_experimental/statespace/filters/kalman_smoother.py
- pymc_experimental/statespace/models/SARIMAX.py
- pymc_experimental/statespace/models/VARMAX.py
- pymc_experimental/statespace/models/structural.py
- pymc_experimental/statespace/models/utilities.py
- pymc_experimental/tests/statespace/test_SARIMAX.py
- pymc_experimental/tests/statespace/test_VARMAX.py
- pymc_experimental/tests/statespace/test_coord_assignment.py
- pymc_experimental/tests/statespace/test_distributions.py
- pymc_experimental/tests/statespace/test_statespace.py
- pymc_experimental/tests/statespace/test_structural.py
- pymc_experimental/tests/statespace/utilities/test_helpers.py
I had originally done this to facilitate out-of-sample sampling tasks, so I could do e.g. `pm.Flat('T', T)`. The result was that all matrices were saved to the `idata`, creating pretty horrible `pm.model_to_graphviz` outputs like this:
This also was extremely memory wasteful. Many of the matrices are not random at all, and they were being saved `(chain, draw)` times. 
After this refactor, the matrices are dynamically rebuilt as needed from the parameter samples. The new graphs look like this:
There are also some en-passant changes to how exogenous data are handled that breaks the Structural example notebook. I will open a new PR after this one to address that, because I think I finally have it set up to handle forecasting with exogenous data. Basically, I was previously treating exogenous …
> Statespace: Don't automatically save statespace matrices as `Deterministic` variables

- pymc_experimental/model/marginal_model.py
- pymc_experimental/tests/model/test_marginal_model.py
The following example defines a 2-state HMM, with a 0.9 transition probability of staying in the same state, and a Normal emission centered around -1 for state 0 and 1 for state 1.
```python
import arviz as az
import numpy as np
import matplotlib.pyplot as plt
from pymc_experimental import MarginalModel
from pymc_experimental.distributions import DiscreteMarkovChain
with MarginalModel() as m:
P = [[0.9, 0.1], [0.1, 0.9]]
init_dist = pm.Categorical.dist(p=[1, 0])
chain = DiscreteMarkovChain("chain", P=P, init_dist=init_dist, steps=10)
emission = pm.Normal("emission", mu=chain * 2 - 1, sigma=0.5)
m.marginalize([chain])
with m:
idata = pm.sample(100)
plt.plot(az.extract(idata)["emission"].values, color="k", alpha=0.03)
plt.yticks([-1, 1])
plt.ylabel("Emission") …
```
> Support HMM via marginalization of DiscreteMarkovChain

- conda-envs/environment-test.yml
- conda-envs/windows-environment-test.yml
- pymc_experimental/distributions/continuous.py
- pymc_experimental/distributions/discrete.py
- pymc_experimental/distributions/timeseries.py
- pymc_experimental/model/marginal_model.py
- pymc_experimental/tests/distributions/test_continuous.py
- pymc_experimental/tests/distributions/test_discrete.py
- pymc_experimental/tests/distributions/test_discrete_markov_chain.py
- pymc_experimental/tests/model/test_marginal_model.py
- requirements.txt
This should let `pymc-experimental` build with pymc v5.11.
This relates to #317
> Update for PyMC v5.11

- pymc_experimental/statespace/core/statespace.py
- pymc_experimental/statespace/models/structural.py
- pymc_experimental/statespace/utils/data_tools.py
- pymc_experimental/tests/statespace/test_structural.py
When I first wrote `StructuralComponent`, I had an idea that every model parameter should have dims associated with it. This had the consequence that even if a parameter should *always* be a scalar, such as standard deviations on shocks, it needed to be given `shape=(1,)` if `dims` were not used. This was a bit silly, so since #296, it has been my intention that scalar-only parameters should be scalars (and have no associated `dims`). #318 points out that the code is currently inconsistent -- some parameters are still having dims generated for them that don't need them, or vice-versa. 
This PR should hopefully clean all this up. Parameters that are always scalars will never have dims associated with them, do not expect a shape argument, and will show `shape=None` in the model info output …
> Bug fixes for `statespace`

- pymc_experimental/model/marginal_model.py
This should be more performant and also faster to compile due to smaller computational graphs.
I've been waiting for the `vectorize` functionality to mature, and I think it's good now
> Use vectorize in `finite_discrete_marginal_rv_logp`

- pymc_experimental/model/transforms/autoreparam.py
- tests/model/transforms/test_autoreparam.py
> Add Exponential distribution to model/transforms/autoreparam.py

- .github/workflows/pypi.yml
Since we don't have access to the project on test.pypi, that step would fail and block any attempt of making new releases.
> Remove test.pypi step on releases

- .pre-commit-config.yaml
- pymc_experimental/__init__.py
- pymc_experimental/distributions/timeseries.py
- pyproject.toml
- tests/distributions/test_discrete_markov_chain.py
Closes #324 
It's just `CategoricalGibbsMetropolis` but accepts `DiscreteMarkovChain` and knows how to get the dimensionality of P.
Once we merge DMC into PyMC we can just extend the CategoricalGibbsMetropolis to accept it
> Specialized DiscreteMarkovChain step sampler

- docs/api_reference.rst
- pymc_experimental/__init__.py
- pymc_experimental/printing.py
- tests/test_printing.py
From https://github.com/pymc-devs/pymc/discussions/7210#discussioncomment-10921154
```python
import numpy as np
from pymc_experimental.printing import model_table
coords = {"subject": range(20), "param": ["a", "b"]}
with pm.Model(coords=coords) as m:
x = pm.Data("x", np.random.normal(size=(20, 2)), dims=("subject", "param"))
y = pm.Data("y", np.random.normal(size=(20,)), dims="subject")
beta = pm.Normal("beta", mu=0, sigma=1, dims="param")
mu = pm.Deterministic("mu", pm.math.dot(x, beta), dims="subject")
sigma = pm.HalfNormal("sigma", sigma=1)
y_obs = pm.Normal("y_obs", mu=mu, sigma=sigma, observed=y, dims="subject")
model_table(m)
```
```
Variable  Expression         Dimensions             
─────────────────────────────────────────────────────
x =  Data …
```
> Summarize model as rich table

- pymc_experimental/statespace/core/statespace.py
- pymc_experimental/statespace/filters/distributions.py
- pymc_experimental/statespace/filters/kalman_filter.py
- pymc_experimental/statespace/models/VARMAX.py
- pyproject.toml
- tests/statespace/test_statespace.py
Enable scenario-based forcasting in VARMAX, SARIMAX, and structural models with regressions.
Couple to-dos before its ready for review:
Otherwise things seem to be working
> Allow forecasting with exogenous variables

- pymc_experimental/statespace/core/statespace.py
- pymc_experimental/statespace/filters/__init__.py
- pymc_experimental/statespace/filters/kalman_filter.py
- tests/statespace/test_distributions.py
- tests/statespace/test_kalman_filter.py
- tests/statespace/test_statespace.py
- tests/statespace/utilities/test_helpers.py
My original vision for `kalman_filter.py` was quite bad. Following `statsmodels`, I made a bunch of classes that instantiate various types of kalman filters, with minor differences between them. The idea was to let the user pick what would work best in his given situation.
Looking at it now, this should all be accomplished via rewrites. Some of it already is. For example, the only difference between the `StandardFilter` and the `SingleTimeSeriesFilter` was that I replaced a matrix inverse with a division. This is done automatically in rewrites, so there's no need for it.
I removed the `SteadyStateFilter` because that never made sense. Instead, all of the filters should be checking for convergence to the steady state -- that will be an upcoming PR.
`CholeskyFilter` has been renamed to …
> Remove dead code from `kalman_filter.py`

- docs/index.rst
Was wondering if the package was on PyPI which it is. The package is also on `conda-forge` but it seems to be [stale](https://anaconda.org/anaconda/pymc-experimental)
> add PyPI details to homepage

- pymc_extras/statespace/models/structural.py
- tests/statespace/test_structural.py
Small bugfix for the `TimeSeasonality` component.
In the classical definition, the `n`-th seasonal effect isn't identified, so `n-1` effects are defined and the transition matrix is:
$$
T= \begin{bmatrix} -1 & -1 & -1 & -1 \\
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
\end{bmatrix}
$$
It's no obvious, so there's a worked example in the API docs for why this does what you want it to do.
I wanted to add an argument that would allow users to handle this normalization themselves if they wished, but it was implemented incorrectly. Now it should work. If you pinky swear that the seasonal effects are normalized (e.g. with ZeroSumNormal prior), you can get a transition matrix like:
$$
T = \begin{bmatrix} 0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 \\
1 & 0 & 0 & 0 
\end{bmatrix}
$$ …
> Fix bug in `TimeSeasonality` when `pop_state` = False

- .github/workflows/pypi.yml
All the changes here are in line with those recently made to the PyMC workflow
> Adapt the GHA PyPI publishing workflow for trusted publishing

- pymc_extras/statespace/core/statespace.py
- tests/statespace/test_statespace.py
Closes #412 
When a user defines a time-varying parameter, he has to give it shape None when building the symbolic graph. This is because the time dimension, unlike all other dimensions, has to remain flexible.
A consequence of this is that the `.type.shape` information will have a `None`. This was assumed to always be known by the `PyMCStateSpace` model class, and was used when making `pm.Flat` RVs in predictive models (`sample_conditional`, `sample_unconditional`, `impulse_response_function`, and `forecast`). PyMC evidently doesn't let you pass `None` as a shape to an RV.
Since `PyMCStateSpace` stores the coords used to fit the model, we can just check those as a fallback to get the expected shapes of RVs. This PR does that. Tasks that require changing the shape of the time dimension …
> Check model coords for unknown shapes when building predictive models

- pymc_extras/model/model_api.py
- tests/model/test_model_api.py
This extends `as_model` to wrap the function arguments in `pm.Data`
The motivation for this is that often what gets resampled when running `sample_posterior_predictive` is dependent on what variables are shared. This makes lots of default behaviour less surprising. It also makes it easier to adapt models made with `as_model` into workflows which rely on `set_data`
> `as_model` wraps function arguments in `Data` if they support it.

- setup.py
As per <https://spdx.org/licenses/>
> Use a valid SPDX identifier for the license

- .github/workflows/pypi.yml
- conda-envs/environment-test.yml
- conda-envs/windows-environment-test.yml
- pymc_extras/__init__.py
- pymc_extras/inference/find_map.py
- pymc_extras/inference/laplace.py
- pymc_extras/model/marginal/marginal_model.py
- pymc_extras/statespace/core/compile.py
- requirements.txt
- tests/test_find_map.py
- tests/test_laplace.py
Specifically responding to suggestions by @theorashid,  but the code is also quite ugly in general. I'd like to think about how it could be done better.
> Bugfixes and Improvements for MAP and Laplace

- conda-envs/environment-test.yml
- conda-envs/windows-environment-test.yml
- pymc_extras/statespace/core/statespace.py
- pymc_extras/statespace/filters/distributions.py
- pyproject.toml
- requirements.txt
Closes #430 
Related to #429 
The latest pytensor release breaks several places in the statespace code. I was using a rewrite to introduce `method='svd'` to multivariate_normal forward samples; this is no longer needed. There was also an `if Variable:` check, which now needs to be `if Variable is not None`.
> Bump PyMC version requirement 

- pymc_extras/inference/pathfinder/importance_sampling.py
- pymc_extras/inference/pathfinder/pathfinder.py
- tests/test_pathfinder.py
**Fix handling of `importance_sampling="none"` or `None` option**
**Changes**
- Modified the handling of importance sampling parameter to treat `"none"` and `None` consistently
- Updated function signatures and documentation to clarify the importance sampling options
**Added/Modified Tests**
- When importance sampling is disabled (None), samples retain shape `(num_paths, num_draws_per_path, N)` (where `N` are the number of model parameters)
- Other importance sampling methods return samples of shape `(num_draws, N)`
- Tighten `np.testing.assert_allclose` tolerance as increasing `jitter` brings parameter estimates closer to the reference value
> Fix: importance_sampling=None produces error

- pymc_extras/statespace/core/statespace.py
- pymc_extras/statespace/filters/distributions.py
- pyproject.toml
- requirements.txt
This is no longer necessary as of `pymc==5.21.1`, because `MvNormal` now has a `method="svd"` argument that can be used. This will also make sampling more robust in non-jax backends, which is also great!
Also updates the version requirement to 5.21.1 as a result
> Remove MvNormalSVD Class

- pymc_extras/statespace/utils/data_tools.py
- tests/statespace/test_coord_assignment.py
Closes #384 
I was assuming that any pandas index of integers was a `RangeIndex`; this will now accept anything. 
One issue is that if the index has holes (like the index goes 0, 1, 3, 4, ...), it will just be totally ignored, and internally we'll treat it *as though* it was continuous. I might be able to check for this, but it might also be the type of thing that you have to trust users to do the right thing with. Open to suggestions.
> Make index check on statespace data less strict

- setup.py
This was missing the pymc 5.21.0 brought in python 3.13 
Reference: 
https://github.com/pymc-devs/pymc/releases
> add python 3.13 to the list

- pymc_extras/inference/laplace.py
- tests/test_laplace.py
When a mean vector has exactly one element, `scipy.stats.multivariate_normal.rvs` squeezes the leading dimension, which was causing errors in `fit_laplace` for models with exactly one parameter.
This PR patches the behavior by adding a check for this corner case.
> Fix bug in fit_laplace when model has exactly one variable

- pymc_extras/inference/fit.py
- pymc_extras/inference/pathfinder/pathfinder.py
Hi all, just a minor change for users who don't have JAX/BlackJAX installed.
Summary of changes:
* Moved the import statement for blackjax to ensure it is only imported when needed.
* Moved blackjax import statement to prevent import errors for users wanting to run pathfinder without JAX/BlackJAX installed.
* Updated the fit function to specify the return type as az.InferenceData.
> Minor fix of blackjax import in fit_pathfinder function

- pymc_extras/inference/pathfinder/pathfinder.py
- tests/test_pathfinder.py
While we figure out how to remove deprecated functionality in #453  this PR should get `main` building properly again!
> Filter warning for batched_dot until we change it

- pymc_extras/inference/fit.py
- pymc_extras/inference/pathfinder/pathfinder.py
- tests/test_pathfinder.py
Fix failed test from PR #443 and replace `pt.batched_dot` with `pt.einsum`
* Modified the calculation of `mu` in `bfgs_sample_dense` and `bfgs_sample_sparse` to use `einsum` instead of the deprecated `batched_dot` function.
* Added calculations for `H_inv` in `bfgs_sample_sparse` to improve readability.
* Renamed `compile_pymc` to `compile` in pathfinder functions to reflect API changes.
* Updated warning filters to ignore UserWarnings related to einsum subscripts.
> Fix failed test related to PR #443 by replacing `pt.batched_dot` with `pt.vectorize(pt.dot,...)`

- pymc_extras/inference/pathfinder/pathfinder.py
The final state is now updated correctly for the progress bar when using Pathfinder.
Closes #456
> Progress bar fix for PF

- docs/api_reference.rst
- pymc_extras/__init__.py
- pymc_extras/inference/__init__.py
- pymc_extras/inference/fit.py
- pymc_extras/inference/laplace.py
- pymc_extras/inference/pathfinder/pathfinder.py
- tests/test_pathfinder.py
* Add initvals to parameters
* Add observations and constants to return value (idata)
* Add both fit_laplace and fit_pathfinder to docs and make fit link to both
* Clean up __init__.py include structure
This arose out of https://discourse.pymc.io/t/pymc-extras-fit-compatibility-with-pm-sample/16763/5
> Make fit_pathfinder more similar to fit_laplace and pm.sample

- pymc_extras/inference/pathfinder/pathfinder.py
Hi all,
This PR fixes https://github.com/pymc-devs/pymc-extras/issues/458.
Adding a regularisation term before the Cholesky decomp step helps avoid inf or nan values.
See working solution after the proposed changes: https://gist.github.com/aphc14/906e9853dba26321fb2ea1ef03cf2c1f
Note that it took approx 1.5 hours to run 2x paths, so I cancelled/interrupted training to stop at 2x paths rather than 4x paths.
> Add regularisation term before Cholesky decomposition

- pymc_extras/inference/pathfinder/lbfgs.py
- pymc_extras/inference/pathfinder/pathfinder.py
- tests/test_pathfinder.py
hey all,
This PR fixes https://github.com/pymc-devs/pymc-extras/issues/445.
During LBFGS iteration, filtering conditions are applied to exclude non-finite values and sharp gradient updates. This PR ensures that when the majority of iterations are excluded, and not enough iterations are stored to run a single PF, that the overall  algorithm continues to the next single PF.
Summary:
- Added entry_condition_met method that combines the logic for determining if LBFGS iterations should be stored.
- Added LBFGS statuses: LOW_UPDATE_MASK_RATIO to inform user when the majority of LBFGS iters aren't being used.
- Added LBFGS statuses: INIT_FAILED_LOW_UPDATE_MASK to inform user when LBFGS failed to initialised due to failing to meet the update conditions.
- Added status messages for …
> Fix LBFGS iteration conditions and status handling

- .github/workflows/test.yml
> Split test suite by folder

- docs/api_reference.rst
- pymc_extras/distributions/__init__.py
- pymc_extras/distributions/transforms/__init__.py
- pymc_extras/distributions/transforms/partial_order.py
- tests/distributions/test_transform.py
This is an implementation of a partial order transform as discussed in https://discourse.pymc.io/t/feature-proposal-poset-order-transform/16753/7
I have tried to make it as generic as possible:
* It takes only the generating DAG and computes the transitive reduction
* It does not assume the DAG is given in topological order but instead handles sorting internally
* It converts the matrix to an adjacency list of incoming nodes, reducing computation for low-degree orders
* It can either take one single DAG for all data or allows specifying a separate DAG for each row
As I am new to contributing to both pymc and pymc-extras, I will likely need some help to get it acceptable.
So far, I have added the code and tests for it, but I don't know how to handle documentation yet. 
Also anything else …
> Added a PartialOrder transform

- conda-envs/environment-test.yml
- conda-envs/windows-environment-test.yml
- pymc_extras/inference/find_map.py
- setup.py
- tests/test_find_map.py
Currently, `fit_MAP` fails on graphs with shared variables when `gradient_backend='jax'`. This is because we are discarding the pytensor function wrapper that helps work with them. This PR rewrites shared variables into constants using `_replace_shared_variables` in this case. This is the same approach used in `pymc.sampling.jax.get_jaxified_graph`
> Fix bug in `fit_MAP` when shared variables are used in graph

- pymc_extras/inference/find_map.py
- pymc_extras/inference/laplace.py
- tests/test_find_map.py
Closes #454 
This PR lets users use the `basinhopping` algorithm to fit PyMC models. This is in the class of simulated annealing algorithms, except that it also runs an inner optimization loop to find the nearest minimum after proposing a new starting position. 
API is pretty clean, if I do say so myself:
```py
with pm.Model() as m:
mu = pm.Normal("mu")
sigma = pm.Exponential("sigma", 1)
pm.Normal("y_hat", mu=mu, sigma=sigma, observed=rng.normal(loc=3, scale=1.5, size=100))
optimized_point = find_MAP(
method="basinhopping",
use_grad=True,
use_hess=False,
use_hessp=True,
progressbar=True,
gradient_backend="pytensor",
compile_kwargs={"mode": "JAX"},
minimizer_kwargs=dict(method="trust-ncg"),
)
```
Gives:
```
Process                            Elapsed   Iteration   Step    Target   Objective …
```
> Allow `method="basinhopping"` in `find_MAP` and `fit_laplace`

- conda-envs/environment-test.yml
- pyproject.toml
Closes #479 . I guess the issue is related to support for `basinhopping`, which requires the latest version of better-optimize.
> Add version pin on better-optimize

- notebooks/VARMAX Example.ipynb
This PR fixes some typographical errors in the SARMA and VARMAX example notebooks.
> Small typos corrections in notebooks SARMA and VARMAX examples

- pymc_extras/statespace/core/statespace.py
- pymc_extras/statespace/filters/distributions.py
- pymc_extras/statespace/filters/kalman_filter.py
- pymc_extras/statespace/filters/kalman_smoother.py
- pymc_extras/statespace/models/ETS.py
- pymc_extras/statespace/models/SARIMAX.py
- pymc_extras/statespace/models/VARMAX.py
- pymc_extras/statespace/models/structural.py
- tests/statespace/core/test_statespace_JAX.py
- tests/statespace/filters/test_kalman_filter.py
- tests/statespace/models/test_ETS.py
- tests/statespace/models/test_SARIMAX.py
- tests/statespace/models/test_VARMAX.py
- tests/statespace/models/test_structural.py
- tests/statespace/test_utilities.py
- tests/statespace/utils/test_coord_assignment.py
Closes #478 
We were previously passing the `mode` argument to scan everywhere in statespace. This isn't strictly necessary, and required a fair amount of bookkeeping. This PR removes the mode argument from all the scans in the repo, and also removes all that bookkeeping.
This will slightly break the user-facing API, because now `build_statespace_graph(data, mode='JAX')` will now raise an error (because you don't need to pass anything). 
It will also now require users to explicitly pass compile_kwargs to all of the sampling functions (`sample_conditional_posterior`, `forecast`, `impulse_response_function`, etc). That's consistent with all PyMC apis, though.
I still need to go through and adjust all the notebooks, but it looks like tests are passing.
> Remove `mode` argument passed from Statespace.build_statespace_graph to scan

- pymc_extras/statespace/filters/kalman_smoother.py
PR addresses #514 by setting `pt.linalg.pinv(hermitian=True)` in Kaman smoother.
> Use `hermitian=True` in `pt.linalg.pinv` in Kalman smoother

- pymc_extras/statespace/core/statespace.py
- tests/statespace/core/test_statespace.py
This PR addresses a bug in the Statespace module where erroneous forecasts were being produced when exogenous variables were present in the model. This PR addresses issue #491.
The issue stemmed from updating the model's data prior to running the model forward up to the forecast's initial time index as specified by the user. This caused the forecasts to be produced using incorrect x0 and P0 initializations at the forecast initial time index. 
The fix ensures that the model is run forward up to the forecast time index and the states (filtered, predicted or smoothed) at that point are frozen using all the observed data. After which new data replacements are made to generate forecasts.
> Forecast exogenous vars bug fix

- pymc_extras/linearmodel.py
Scikit-learn 1.7.0 wants all `LinearModel` estimators to also have a `BaseEstimator` mixin to the far right. This is currently raising a DepreciationWarning, but will switch to an error at some point.
> Add `BaseEstimator` mixin to `LinearModel`

- pyproject.toml
Preliz is not imported at the top level so this makes it optional dependency. I was having issues with preliz since it has numba as a dependency which has no python only wheel making pyodide not able to use it.
> Make preliz optional

- conda-envs/environment-test.yml
- pyproject.toml
Otherwise we risk pulling an ancient version.
Without this, it's not clear why we need Python 3.11
> Add lower bound on preliz version

- pymc_extras/inference/laplace.py
- tests/test_laplace.py
Addresses #342.
This PR should add:
-  [x] ```get_conditional_gaussian_approximation```
To get the mode and the laplace approximation at that point.
Contingent on pymc-devs/pytensor#1182, as it uses ```pytensor.tensor.optimize.minimize``` to find the mode (and hessian at that point).
> Implement a minimizer for INLA

- conda-envs/environment-test.yml
- pymc_extras/inference/pathfinder/pathfinder.py
- pyproject.toml
import progress bar functions from `pymc.progress_bar` instead of `pymc.util`
This addresses the issue in #541 
What I am not sure of though is what happens if a user wants to use the latest `pymc-extras` version with `pymc<5.24.0`?
> fix import error due to moving progress bar functions in latest pymc

- pymc_extras/inference/laplace_approx/find_map.py
- tests/inference/laplace_approx/test_find_map.py
- tests/inference/laplace_approx/test_laplace.py
Bugfix for find_MAP. The following code currently errors:
```py
with pm.Model() as m:
mu = pm.Normal("mu", 0, 1)
sigma = pm.Exponential("sigma", 1)
y_hat = pm.Normal("y_hat", mu=mu, sigma=sigma, observed=np.random.normal(size=10))
idata = find_MAP(
model=m,
method="L-BFGS-B",
use_grad=True,
use_hess=False,
use_hessp=False,
progressbar=False,
compile_kwargs={"mode": "JAX"},
)
```
Because the model argument is not correctly forwarded everywhere it is needed inside find_MAP. This patches the bug and adds a regression test.
> Forward model argument to  add_fit_to_inference_data in find_MAP

- pymc_extras/statespace/models/structural/core.py
- tests/statespace/models/structural/test_core.py
Closes #544 
Hidden state extraction is currently bugged when there are multiple observed. This patches the bug by correctly summing each observed state's subset of states, then returning one new state per observed.
The linked issue pointed out that Autoregressive was broken, but actually so is any component with `combined_hidden_states=True`. This PR fixes all such components.
> Fix hidden state extraction where there are multiple observed states

- pymc_extras/statespace/models/structural/components/autoregressive.py
- pymc_extras/statespace/models/structural/core.py
Small fix for #546 + a typo fix in `core`'s docstrings
> Fix AR labeling + `core` docstrings typo

- pymc_extras/statespace/core/statespace.py
- pymc_extras/statespace/filters/kalman_filter.py
- pymc_extras/statespace/utils/constants.py
- tests/statespace/core/test_statespace.py
- tests/statespace/models/test_SARIMAX.py
- tests/statespace/models/test_VARMAX.py
- tests/statespace/utils/test_coord_assignment.py
This addresses #521, allows state space users to sample filtered|predicted|smoothed|observed states|covariances using a utility that is consistent with PyMC workflow of sample -> sample_posterior.
> added sample_filter_outputs utility and accompanying simple tests

- pymc_extras/statespace/models/structural/components/autoregressive.py
- pymc_extras/statespace/models/structural/components/cycle.py
- pymc_extras/statespace/models/structural/components/level_trend.py
- pymc_extras/statespace/models/structural/components/measurement_error.py
- pymc_extras/statespace/models/structural/components/regression.py
- pymc_extras/statespace/models/structural/components/seasonality.py
- pymc_extras/statespace/models/structural/core.py
- tests/statespace/models/structural/components/test_autoregressive.py
- tests/statespace/models/structural/components/test_cycle.py
- tests/statespace/models/structural/components/test_level_trend.py
- tests/statespace/models/structural/components/test_measurement_error.py
- tests/statespace/models/structural/components/test_regression.py
- tests/statespace/models/structural/components/test_seasonality.py
- tests/statespace/models/structural/test_against_statsmodels.py
This PR allows multivariate components to share latent states between observed states. For example, if we want two states to have a shared component and an idiosyncratic component, as in:
$$
\begin{align}
a_t &= x_t + y_t \\
b_t &= x_t + z_t \\
\end{align}
$$
This can be accomplished as follows:
```py
shared_level = st.LevelTrendComponent(
name="shared_level",
order=1,
innovations_order=1,
observed_state_names=["a", "b"],
share_states=True,
)
individual_level = st.LevelTrendComponent(
name="individual_level",
order=1,
innovations_order=1,
observed_state_names=["a", "b"],
)
mod = (shared_level + individual_level).build(verbose=False)
```
This will require a refactor for each component to add the `shared_states` argument. Here's the TODO list:
> Allow multivariate components to share latent states

- pymc_extras/statespace/__init__.py
- pymc_extras/statespace/core/statespace.py
- pymc_extras/statespace/models/SARIMAX.py
- pymc_extras/statespace/models/__init__.py
- pymc_extras/statespace/models/structural/components/autoregressive.py
- pymc_extras/statespace/utils/constants.py
- tests/statespace/core/test_statespace.py
- tests/statespace/models/structural/components/test_regression.py
- tests/statespace/models/test_SARIMAX.py
Exogenous regressors are added via a time-varying observation bias to keep the statespace as small as possible.
We could consider allowing something fancier, but this is a good v0.
> Allow exogenous regressions in `BayesianSARIMAX`

- pymc_extras/statespace/models/VARMAX.py
- tests/statespace/models/test_VARMAX.py
This PR adds support for exogenous variables in `BayesianVARMAX` via the observation intercept. Same deal as SARIMAX -- it's implemented in a way that minimizes the number of states in the system.
Unlike Statsmodels, we have support for each observed state to have its own regressors by passing a dictionary. If you just pass a list, everyone shares the same data.
Example 1: Everyone shares data, data names are auto-assigned 
```py
mod = BayesianVARMAX(
endog_names=["y1", "y2", "y3"],
order=(1, 0),
k_exog=2,
)
```
Example 2: Everyone shares data, data names are provided 
```py
mod = BayesianVARMAX(
endog_names=["y1", "y2", "y3"],
order=(1, 0),
exog_state_names=['x1', 'x2']
)
```
Example 3: Each observes state (endogenous state) has its own exogenous regressors. y3 has no exogenous …
> Allow exogenous regressors in `BayesianVARMAX`

- pymc_extras/inference/laplace_approx/find_map.py
- pymc_extras/inference/laplace_approx/idata.py
- pymc_extras/inference/laplace_approx/laplace.py
- tests/inference/laplace_approx/test_find_map.py
Small optimization to `find_MAP`. We were always computing the hessian after fitting, which can be really expensive on high-dimensional problems. The hessian is needed for laplace, but not for MAP itself. This PR adds a `compute_covariance`, which is False by default.
> Allow skipping covariance computation in `find_MAP`

- pymc_extras/statespace/models/VARMAX.py
- tests/statespace/models/test_VARMAX.py
VARMAX forecasting is broken when there is no exogenous data because the return value of `data_info` is incorrect. I also added tests that would have caught this bug.
> Always return dictionary from data_info

- pyproject.toml
These don't actually make our tests fail, but the CI is currently all failing as a result.
> Ignore BLAS warning in tests
